### ISSUE TITLE
Does hot-reloading work on MacOS ?

### ISSUE THREAD

**Issue by vortex314** [MoAlyousef/fltk-decl#1]
Very nice development, I was working on the same concept to have MQTT customisable dashboards.
How does the hot-reload work ? I was expecting that by changing the config file , the GUI would be automatically recreated.
When I save the file nothing happens, restarting the application creates the updated window. Did I miss something ?
The code is from one of the examples.
```
fn main() {
    app::GlobalState::new(State { count: 0 });
    DeclarativeApp::new_json(200, 300, "MyApp", PATH)
        .run(|_win| {
            app::set_scheme(app::Scheme::Oxy);
            if let Some(mut btn) = app::widget_from_id::<button::Button>("inc") {
                btn.set_callback(btn_cb);
            }
            if let Some(mut btn) = app::widget_from_id::<button::Button>("dec") {
                btn.set_callback(btn_cb);
            }
        })
        .unwrap();
}
```

**Comment by MoAlyousef** [comment]
Thank you
It should work but I haven’t tried on macos yet, will do when I get home. 
This crate uses the notify crate, maybe there are issues on macos.

**Comment by MoAlyousef** [comment]
So macos uses a different event for file modification, I've pushed a fix and released a new version.

**Comment by vortex314** [comment]
Hi, thanks for the swift follow-up. Works as expected. Great job.
