### ISSUE TITLE
[Feature Request]Please add the ability to specify a widgets height in the declarative file

### ISSUE THREAD

**Issue by stevehello166** [MoAlyousef/fltk-decl#2]
Please add the ability to specify a widgets height in the declarative file(json, json5, etc), this is a minor inconvenience however it would make writing UI's way easier.

ps. thanks for all the work you've done on this project.

**Comment by MoAlyousef** [comment]
Hello
This should be supported in 0.2.5 which I just published

**Comment by stevehello166** [comment]
thanks i will update immediately
